import { Exercise } from '../domain/exercise.entity';
import { ExerciseCategory } from '../common/enums';

/**
 * The shared starter library everyone sees (ownerId null). The API makes
 * sure these exist on every startup, so a fresh production database has
 * them without running the demo seed.
 */
export const BUILT_IN_EXERCISES: (Pick<Exercise, 'name' | 'category' | 'primaryMuscle'> &
  Partial<Pick<Exercise, 'isCompetitionLift'>>)[] = [
  { name: 'Back Squat', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads', isCompetitionLift: true },
  { name: 'Bench Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest', isCompetitionLift: true },
  { name: 'Deadlift', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Posterior Chain', isCompetitionLift: true },
  { name: 'Overhead Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Shoulders' },
  { name: 'Front Squat', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Romanian Deadlift', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Hamstrings' },
  { name: 'Barbell Row', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Back' },
  { name: 'Pull-Up', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Back' },
  { name: 'Incline Dumbbell Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Leg Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Lat Pulldown', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Back' },
  { name: 'Dumbbell Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Biceps' },
  { name: 'Triceps Pushdown', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Triceps' },
  { name: 'Lateral Raise', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Shoulders' },
  { name: 'Leg Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Hamstrings' },
  { name: 'Leg Extension', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Quads' },
  { name: 'Calf Raise', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Calves' },
  { name: 'Face Pull', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Rear Delts' },

  // More options: variations, machines and accessories for every body part.
  { name: 'Pause Squat', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Box Squat', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Safety Bar Squat', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Hack Squat', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Goblet Squat', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Bulgarian Split Squat', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Walking Lunge', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Step-Up', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Quads' },
  { name: 'Close-Grip Bench Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Triceps' },
  { name: 'Pause Bench Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Incline Bench Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Decline Bench Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Dumbbell Bench Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Larsen Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Floor Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Machine Chest Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Dip', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Push-Up', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Chest' },
  { name: 'Cable Fly', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Chest' },
  { name: 'Pec Deck', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Chest' },
  { name: 'Dumbbell Fly', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Chest' },
  { name: 'Sumo Deadlift', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Posterior Chain' },
  { name: 'Deficit Deadlift', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Posterior Chain' },
  { name: 'Block Pull', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Posterior Chain' },
  { name: 'Trap Bar Deadlift', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Posterior Chain' },
  { name: 'Good Morning', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Hamstrings' },
  { name: 'Stiff-Leg Deadlift', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Hamstrings' },
  { name: 'Nordic Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Hamstrings' },
  { name: 'Seated Leg Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Hamstrings' },
  { name: 'Hip Thrust', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Glutes' },
  { name: 'Glute Bridge', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Glutes' },
  { name: 'Cable Kickback', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Glutes' },
  { name: 'Back Extension', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Glutes' },
  { name: 'Hip Abduction', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Glutes' },
  { name: 'Hip Adduction', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Adductors' },
  { name: 'Chin-Up', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Back' },
  { name: 'Pendlay Row', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Back' },
  { name: 'Dumbbell Row', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Back' },
  { name: 'Seated Cable Row', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Back' },
  { name: 'T-Bar Row', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Back' },
  { name: 'Chest-Supported Row', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Back' },
  { name: 'Straight-Arm Pulldown', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Back' },
  { name: 'Pullover', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Back' },
  { name: 'Barbell Shrug', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Traps' },
  { name: 'Dumbbell Shrug', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Traps' },
  { name: 'Push Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Shoulders' },
  { name: 'Seated Dumbbell Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Shoulders' },
  { name: 'Arnold Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Shoulders' },
  { name: 'Machine Shoulder Press', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Shoulders' },
  { name: 'Cable Lateral Raise', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Shoulders' },
  { name: 'Front Raise', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Shoulders' },
  { name: 'Upright Row', category: ExerciseCategory.COMPOUND, primaryMuscle: 'Shoulders' },
  { name: 'Reverse Pec Deck', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Rear Delts' },
  { name: 'Rear Delt Fly', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Rear Delts' },
  { name: 'Barbell Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Biceps' },
  { name: 'EZ-Bar Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Biceps' },
  { name: 'Hammer Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Biceps' },
  { name: 'Preacher Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Biceps' },
  { name: 'Incline Dumbbell Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Biceps' },
  { name: 'Cable Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Biceps' },
  { name: 'Skull Crusher', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Triceps' },
  { name: 'Overhead Triceps Extension', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Triceps' },
  { name: 'Dumbbell Kickback', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Triceps' },
  { name: 'Wrist Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Forearms' },
  { name: 'Reverse Curl', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Forearms' },
  { name: "Farmer's Carry", category: ExerciseCategory.COMPOUND, primaryMuscle: 'Forearms' },
  { name: 'Standing Calf Raise', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Calves' },
  { name: 'Seated Calf Raise', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Calves' },
  { name: 'Plank', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Abs' },
  { name: 'Hanging Leg Raise', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Abs' },
  { name: 'Cable Crunch', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Abs' },
  { name: 'Ab Wheel Rollout', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Abs' },
  { name: 'Russian Twist', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Abs' },
  { name: 'Pallof Press', category: ExerciseCategory.ISOLATION, primaryMuscle: 'Abs' },
];
